### PR TITLE
Update for stabilized io::Error

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Yay, and then we'll be on stable Rust. :-)

I'll merge once the new nightly lands.

**Comment by BurntSushi** [comment]
Looks like the nightly has been updated, but testing is blocking on the `rand` crate being updated: https://github.com/rust-lang/rand/pull/42

**Comment by sfackler** [comment]
rand's up to date now.

**Comment by TyOverby** [comment]
@BurntSushi: could you publish a new cargo version as well?

**Comment by BurntSushi** [comment]
Uploaded to crates.io in `0.3.5`. Sorry about the delay, I'm at work and it's a busy day. :P

**Comment by TyOverby** [comment]
Thanks!

**Pull request merged**
