### PR TITLE
Add examples for {u,i}128 methods

### PR DESCRIPTION
**Pull request by SamWhited**
More examples for the new 128 bit methods

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks!

**Comment by SamWhited** [comment]
Oh wow, too fast for me :) I pushed this and then realized I hadn't committed all of them, another PR coming in shortly…

**Comment by BurntSushi** [comment]
@SamWhited Drats. I'll slow it down next time. :-)

**Comment by SamWhited** [comment]
Heh, no, no, my fault; thanks for being such an active maintainer!

**Pull request merged**
