### PR TITLE
Remove custom error type

### PR DESCRIPTION
**Pull request by lukesteensen**
Now that 1.6 is released, all of this functionality is stable in the standard library.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Yeah, this is sweet. Getting of the error type is nice.

I'm not a fan of requiring the latest stable Rust *immediately*, but this will require a 0.x version bump. So folks that want to support older versions of Rust can continue using 0.4, while the error type is removed in 0.5. Does that sound reasonable?

cc @nwin @TyOverby @sfackler

**Comment by lukesteensen** [comment]
Absolutely, I figured a version bump would be in order.

**Comment by sfackler** [comment]
Yep, landing it now with a version bump seems reasonable to me. I try to support one version back, so I probably wouldn't update my dependencies until 1.7 lands, but definitely on board with this change.

**Comment by cesarb** [comment]
The main motivation for the [read_exact RFC](https://github.com/rust-lang/rfcs/blob/master/text/0980-read-exact.md) was exactly that: to standardize the error return for fixed-size reading/writing helper functions. This pull request completes the work I started by rewriting that RFC, and therefore it would be really cool to see it merged and released.

**Comment by matt2xu** [comment]
Great to see this pull request! Do you plan to release it when the next stable version of Rust (1.7) is released, in a month or so, or at a different date?

**Comment by BurntSushi** [comment]
@matt2xu Waiting one release cycle + semver bump sounds about right.

**Comment by lfairy** [comment]
I had the same idea just earlier today!

Rust 1.7 was released earlier this week, so I think now's a good time to merge :+1:

**Comment by lukesteensen** [comment]
@BurntSushi let me know if there's anything I can do to help get this merged. Really looking forward to having this functionality in a released version. Thanks!

**Comment by BurntSushi** [comment]
@lukesteensen I'm surprised to see folks so eager to have this removed! :P

I'm happy to merge as soon as I can. One thing: can you add `[breaking-change]` to the commit message that removes the custom error type? Please also include a short explanation of how to fix it. (In this case, I think callers need to "replace uses of `byteorder::Error` with `std::io::Error`.)

**Comment by TyOverby** [comment]
Hey, I just noticed that I was mentioned in this issue.  Sounds good to me!

**Comment by lukesteensen** [comment]
@BurntSushi Just rebased with an expanded commit message. Let me know if there's anything else I can improve!

I think the big win here is in simpler composability with other functions returning `std::io::Error`, especially `read_exact`. Handling two different but equivalent versions of `UnexpectedEofError` is a bit of a pain.

**Comment by BurntSushi** [comment]
Fantastic, thank you! And thanks for your patience. :-)

**Comment by BurntSushi** [comment]
Released on crates.io in `0.5.0`!

**Comment by lukesteensen** [comment]
Awesome! Thanks for making such a useful library :smile:

**Pull request merged**
