### PR TITLE
bring the changelog up to date

### LINKED ISSUE #176: Changelog is not up to date
Current version of byteorder is 1.4.3, but the changelog ends with 1.3.4: https://github.com/BurntSushi/byteorder/blob/abffade8232229db557e0a30c395963071624b2b/CHANGELOG.md

It would be nice if someone can add the changes from the more recent versions. :)

### PR DESCRIPTION
**Pull request by striezel**
Closes #176.

I hope I did not miss to document any important change here.

### CODE REVIEW

**Comment by striezel** [comment]
@BurntSushi
Feel free to squash this into one commit in the case that it gets merged. I just thought it might be easier to review when there is one commit for each version bump.

**Comment by striezel** [comment]
@BurntSushi: Just a friendly reminder that is has been almost a year since the PR was created.

If there is anything wrong with the changes in this PR and this is causing the lack of feedback here, then please let me know so I can fix it.

**Comment by striezel** [comment]
@BurntSushi: Just a friendly reminder that is has been over a year since the PR was created.

If there is anything wrong with the changes in this PR and this is causing the lack of feedback here, then please let me know so I can fix it.

**Comment by striezel** [comment]
Hmm. It probably wouldn't have hurt to add those changes before adding the warning in commit 62b0e31f277e34e89fb7060f6bae5be16f05d00c. :disappointed: The entries for some of the newer releases are already here, so it wouldn't have been much work to just merge them.

**Comment by BurntSushi** [comment]
It's easy to look at any one particular PR and say, "just merge it." But I would have had to review it, ask for changes (or do them myself) and check that everything is correct. What may seem to you like a matter of just clicking a button is to me at best 10 minutes of review and at worst tens of minutes. Now when you take that and put it into the context of how much free time I have and how these sorts of things compound over the dozens of projects I maintain, the time really starts to add up.

As a maintainer, I look for shortcuts where reasonable to reduce the burden. Changelogs for small low-activity projects like these are easy to drop. And if I'm dropping it, then dropping the (at least) ten minutes to review a PR for it is another shortcut.

Sorry this didn't get merged.

**Pull request closed without merging**
