### PR TITLE
i128 support

### PR DESCRIPTION
**Pull request by quininer**
:D

### CODE REVIEW

**Comment by BurntSushi** [comment]
Can you please add tests and documentation?

**Comment by BurntSushi** [comment]
And please also write a better commit message.

**Comment by quininer** [comment]
I have no way to use `qc_byte_order!` and `qc_bytes_ext!` to test `i128`, because `rand` does not support.
should I write a new test code for `i128`? or let `rand` support `i128`?

**Comment by BurntSushi** [comment]
We cannot merge this without tests.

We can either wait for `rand` to support `i128` (and thus block this PR) or figure out some work around. For example, by rewriting the existing tests to, perhaps, use a custom trait. We can then implement that trait using rand for everything except for `i128`, and then implement it for `i128` by, say, generating two `u64`s.

We probably also need to add `{read_uint,read_int,write_uint,write_int}128` methods too. And those will have to be done in this initial PR since adding them later is a breaking change.

**Comment by quininer** [comment]
travis-ci rustc still does not support i128...

**Comment by oli-obk** [comment]
travis passes now apparently

**Comment by oli-obk** [comment]
@BurntSushi could you have a look again? There are tests now and they pass on travis

**Comment by oli-obk** [comment]
ping @BurntSushi

**Comment by BurntSushi** [comment]
@oli-obk Sorry, but could you also rebase and squash this down to one commit? Thanks!

**Comment by oli-obk** [comment]
@BurntSushi I think you meant @quininer ;)

**Comment by oli-obk** [comment]
@BurntSushi note: you can select squash and merge in the github merge button iirc

**Comment by BurntSushi** [comment]
@oli-obk D'oh. Sorry. It's early.

**Comment by BurntSushi** [comment]
@oli-obk Yeah I know, but lately I've been trying to eliminate merge commits from my repos. (I also feel like the PR author should write the commit message, but if I squash and merge, I have to do it.)

**Comment by oli-obk** [comment]
It wouldn't produce a merge commit in the squash case.

Not sure what the commit message would be, never tried it...

**Comment by quininer** [comment]
Ok, I admit i'm not good at using `git rebase`. :(

**Comment by BurntSushi** [comment]
@quininer No worries! You still had a stray merge commit in there, so I just went ahead and cleaned it up. This PR was merged in https://github.com/BurntSushi/byteorder/commit/cac7fc4798425acf63131897eeb04e73a48de91c. Thanks so much!!!

**Pull request closed without merging**
