### PR TITLE
make int->float conversion a transmute

### PR DESCRIPTION
**Pull request by Gankro**
This is the mirror commit to https://github.com/rust-lang/rust/pull/46012

### CODE REVIEW

**Comment by Gankro** [comment]
Changed to transmute based on feedback on upstream Rust change.

Note that this basically gives us a cross-platform guarantee of if you feed in a NaN from one end, you get "some" NaN on the other end. The bits will match, but signaling-ness *may* toggle.

**Comment by BurntSushi** [comment]
@Gankro Thanks! I think you need to update (or remove?) the `read_snan` test though, which was made to test the masking implementation.

> The bits will match, but signaling-ness may toggle.

Could you say more about this? I don't think I understand. If the bits don't change, how does signaling-ness change? (Please keep in mind that my knowledge of floating is quite simplistic.)

**Comment by Gankro** [comment]
Basically until 2008, IEEE didn’t spec how to determine signalingness. Most platforms ended up picking the one that was later spec’d but e.g. MIPS picked the  opposite interpretation of the signaling bit. So a signaling NaN on x86 is quiet on MIPS and vice-versa.

**Comment by Gankro** [comment]
This leaves any protocol which wishes to communicate between two systems with different signaling interpretations with a choice: either guarantee the NaN payload is preserved, or guarantee the signalingness is preserved.

For various reasons signaling is a bit of a mess, so it’s hard for it to be useful, making my preference preserving the NaN payload (which is also the easiest impl: transmute on both sides).

**Comment by Gankro** [comment]
If you prefer the other option, the "obviously correct" canonicalization is still the 2008 spec, which still makes almost every platform read/write with transmute. MIPS and the few other "rogue" platforms would need to check if the value is NaN and flip a bit on read/write (similar to the current reading code).

**Comment by BurntSushi** [comment]
@Gankro Ah thanks for explaining that, I finally understand. Keeping it as a transmute is fine with me!

**Comment by BurntSushi** [comment]
(But this does still need to remove the snan test!)

**Comment by Gankro** [comment]
Yeah sorry I'm waiting to get the r+ on the upstream patch to finish this
up.

**Comment by Gankro** [comment]
Accepted upstream, pushed test removal.

**Pull request merged**
